### ISSUE TITLE
Sentry not picking up fatalError text in crash reports

### ISSUE THREAD

**Issue by nbrooke** [steamclock/steamclog-swift#65]
Currently it looks like any intentional crashes from `clog.fatal` / `fatalError` don't get the text in the fatal error function call attached to them (in any way I could find).

Seems like it should be possible for this to work, and is maybe just something we have misconfigured, and even if not, we should be able to work around it by just making sure a breadcrumb with the fatal error text gets added right before the crash.

**Comment by nbrooke** [comment]
It's also possible the text IS there somewhere and I just couldn't find it. Even if that's the case, I think we should probably include the error text as a breadcrumb, since if it's challenging to find, it'd be nice if it was just somewhere more front and centre.

**Comment by nbrooke** [comment]
#69 partially fixes this, it adds the error text as a breadcrumb on the actual crash report (and also fixes an issue where previously it would generate TWO issues frequently from crashes, one reported error that did have the correct title, and then a crash that did not have that text). So it's at least there somewhere now, but it still won't show up for raw fatal errors, nor will the text be the issue title which would be desirable, so we should investigate further still, and possible file a bug against the Sentry iOS SDK (since it seems like this should just be handled)

**Comment by jacobminer** [comment]
It looks like the fix for this was merged recently! 
https://github.com/getsentry/sentry-cocoa/pull/1596, and should be available in Sentry [7.8.0](https://github.com/getsentry/sentry-cocoa/releases/tag/7.8.0)
