### ISSUE TITLE
Rework preset log levels

### ISSUE THREAD

**Issue by brendanlensink** [steamclock/steamclog-swift#77]
We've run into problems on multiple projects now where the `release` default not logging anything to disk has made issues harder to diagnose and fix. It may be a good idea to reconsider this and at least log `warn` and above to disk, although I think an argument could be made to include `info` as well.

**Comment by nbrooke** [comment]
One thing to consider here also: do we want to separate more what we are logging to disk vs. automatically to filed sentry issue. The main rationale behind not doing much logging in the normal `.release` level was to avoid potentially leaking any personal info with the automatic crash / non-fatal reporting without the user knowing about it, but the on disk logs are somewhat less sensitive in that way, in that with the on disk logs we don't do anything with them except as part of a user request (sending the email). 

If the on-disk logs has more details automatically, and then we had some sort of privacy warning when you re emailing them, I feel like that would provide a reasonable balance of privacy and debuggability.

**Comment by brendanlensink** [comment]
After some discussion in tech working group, we'd like to make these changes:
- Change `release` log level to log down to `info` on disk
- Change `releaseAdvanced` log level to log down to `debug` on disk

We also want to spend some time clarifying the usage of `info`, `debug`, and `verbose` in code to ensure that we aren't logging way too much to disk now that info is always logged.

**Comment by nbrooke** [comment]
Two additions / tweaks:
  - We should also be logging the `info` level to Sentry in `release`, and `debug` in `releasedAdvanced` (right now it only goes down to `warn` for `release` and `info` for `releaseAdvanced`)
  - Another part of the clarification of usage is making sure that nothing super-sensitive is being logged at the `info` level. Anything that might be a privacy issue should definitely only be at debug, where we don't get it until the user has turned that on.
